name: SonarCloud Scan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  sonarcloud-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:/home/runner/.dotnet/tools"

      - name: Restore dependencies
        run: |
          dotnet restore

      - name: Run SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:$SONAR_PROJECT_KEY \
            /o:$SONAR_ORGANIZATION \
            /d:sonar.host.url=$SONAR_HOST_URL \
            /d:sonar.login=$SONAR_TOKEN
          dotnet build
          dotnet test
          dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
        env:
          SONAR_PROJECT_KEY: "${{ secrets.SONAR_PROJECT_KEY_BACKEND }}"
          SONAR_ORGANIZATION: "${{ secrets.SONAR_ORGANIZATION }}"
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN_BACKEND }}"

  sonarcloud-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.2.0

      - name: Install dependencies
        run: npm install

      - name: Run tests and collect coverage
        run: npm run test-coverage

      - name: Build
        run: npm run build

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarCloud analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.organization=$SONAR_ORGANIZATION \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
            -Dsonar.exclusions=src/contexts/**/*,src/interface/**/*,src/layouts/**/*,src/mocks/**/*,src/routes/**/*,src/services/**/*
        env:
          SONAR_PROJECT_KEY: "${{ secrets.SONAR_PROJECT_KEY_FRONTEND }}"
          SONAR_ORGANIZATION: "${{ secrets.SONAR_ORGANIZATION }}"
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN_FRONTEND }}"
